/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    CContainer: typeof import('./../src/components/c-container/index.vue')['default']
    CHeader: typeof import('./../src/components/c-header/index.vue')['default']
    CLine: typeof import('./../src/components/c-line.vue')['default']
    LangSelect: typeof import('./../src/components/lang-select/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
